//@version=6
indicator(title="Top Right Watermark", shorttitle = "TR Watermark", overlay = true)

// Inputs
//{
wm_size     = input.string(size.huge, 
                       title = "watermark size",
                       options = [size.tiny, size.small, size.normal, size.large, size.huge],
                       inline = "WM")
tf_style    = input.string("TradingView", 
                       title = "Timeframe Style",
                       options = ["TradingView", "MetaTrader"]),
wm_col      = input.color (color.new(color.gray, 70), 
                       title = "",                                
                       inline = "WM")
wm_posV     = input.string("top",                 
                       title = "",
                       options = ["top", "middle", "bottom"],                                
                       inline = "WM")
wm_posH     = input.string("right", 
                       title = "",
                       options = ["left", "center", "right"],                                
                       inline = "WM")
line1       = input.string("Ticker", options = ["Timeframe", "Ticker", "Exchange", "Custom Text", "Empty"])
line2       = input.string("Timeframe",    options = ["Timeframe", "Ticker", "Exchange", "Custom Text", "Empty"])
line3       = input.string("Empty",      options = ["Timeframe", "Ticker", "Exchange", "Custom Text", "Empty"])
custom_txt  = input.string("custom text", 
                       title = "custom text")
//}

// Set Watermark
//{
var watermark = table.new(wm_posV + "_" + wm_posH, 1, 1)

// Get current timeframe period
period = timeframe.period
string watermark_txt = ""
string TF_txt        = ""
string Ticker_txt    = ""
string Exchange_txt  = ""

TF_txt := switch period
    "1S"      => tf_style == "TradingView" ? "1s" : "S1"
    "5S"      => tf_style == "TradingView" ? "5s" : "S5"
    "10S"     => tf_style == "TradingView" ? "10s" : "S10"
    "15S"     => tf_style == "TradingView" ? "15s" : "S15"
    "30S"     => tf_style == "TradingView" ? "30s" : "S30"
    "45S"     => tf_style == "TradingView" ? "45s" : "S45"
    "1"       => tf_style == "TradingView" ? "1m" : "M1"
    "2"       => tf_style == "TradingView" ? "2m" : "M2"
    "3"       => tf_style == "TradingView" ? "3m" : "M3"
    "5"       => tf_style == "TradingView" ? "5m" : "M5"
    "6"       => tf_style == "TradingView" ? "6m" : "M6"
    "7"       => tf_style == "TradingView" ? "7m" : "M7"
    "10"      => tf_style == "TradingView" ? "10m" : "M10"
    "12"      => tf_style == "TradingView" ? "12m" : "M12"
    "15"      => tf_style == "TradingView" ? "15m" : "M15"
    "30"      => tf_style == "TradingView" ? "30m" : "M30"
    "45"      => tf_style == "TradingView" ? "45m" : "M45"
    "60"      => tf_style == "TradingView" ? "1H" : "H1"
    "120"     => tf_style == "TradingView" ? "2H" : "H2"
    "180"     => tf_style == "TradingView" ? "3H" : "H3"
    "240"     => tf_style == "TradingView" ? "4H" : "H4"
    "300"     => tf_style == "TradingView" ? "5H" : "H5"
    "360"     => tf_style == "TradingView" ? "6H" : "H6"
    "420"     => tf_style == "TradingView" ? "7H" : "H7"
    "480"     => tf_style == "TradingView" ? "8H" : "H8"
    "540"     => tf_style == "TradingView" ? "9H" : "H9"
    "600"     => tf_style == "TradingView" ? "10H" : "H10"
    "660"     => tf_style == "TradingView" ? "11H" : "H11"
    "720"     => tf_style == "TradingView" ? "12H" : "H12"
    "1D"      => tf_style == "TradingView" ? "1D" : "D1"
    "2D"      => tf_style == "TradingView" ? "2D" : "D2"
    "3D"      => tf_style == "TradingView" ? "3D" : "D3"
    "1W"      => tf_style == "TradingView" ? "1W" : "W1"
    "1M"      => tf_style == "TradingView" ? "1M" : "MN"
    => period

Ticker_txt := syminfo.ticker

Exchange_txt := syminfo.prefix

line1_txt = switch line1
    "Timeframe"     => TF_txt
    "Ticker"        => Ticker_txt
    "Exchange"      => Exchange_txt
    "Custom Text"   => custom_txt
    "Empty"         => ""

line2_txt = switch line2
    "Timeframe"     => TF_txt
    "Ticker"        => Ticker_txt
    "Exchange"      => Exchange_txt
    "Custom Text"   => custom_txt
    "Empty"         => ""

line3_txt = switch line3
    "Timeframe"     => TF_txt
    "Ticker"        => Ticker_txt
    "Exchange"      => Exchange_txt
    "Custom Text"   => custom_txt
    "Empty"         => ""

watermark_txt := 
                                 line1_txt +
 (line1_txt == "" ? "" : "\n") + line2_txt +
 (line2_txt == "" ? "" : "\n") + line3_txt

//
if barstate.isfirst
    table.cell_set_text      (watermark, 0, 0, text       = watermark_txt)
    table.cell_set_text_color(watermark, 0, 0, text_color =  wm_col)
    table.cell_set_text_size (watermark, 0, 0, text_size  = wm_size)
//}